feat: add fastapi + service_info endpoint
GenomicMedLab/software-templates pull request #78
Opened 2024-12-31 19:14 UTC by jsstevenson

2025-01-03 14:19 UTC, jsstevenson commented
oh, a possible TODO here is that ruff includes a fastapi-specific set of lints we could use

2025-01-03 15:59 UTC, korikuzma submitted a review, later dismissed
Sweet 🚀

2025-01-06 13:22 UTC, korikuzma approved these changes

2025-01-08 13:56 UTC, korikuzma requested changes

2025-01-08 13:56 UTC, korikuzma commented on python/{{cookiecutter.project_slug}}/pyproject.toml
Looks like there's still some merge conflicts that need resolved

2025-01-08 14:46 UTC, jsstevenson commented on python/{{cookiecutter.project_slug}}/pyproject.toml
good catch

2025-01-08 15:23 UTC, korikuzma approved these changes

2025-01-08 15:25 UTC, merged